<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="nul" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dotnet.Script.Core" Version="1.6.0" />
    <PackageReference Include="Dotnet.Script.DependencyModel" Version="1.6.0" />
    <PackageReference Include="Dotnet.Script.DependencyModel.Nuget" Version="1.6.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.11.0" />
    <PackageReference Include="Google.Protobuf" Version="3.28.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="NetCoreServer" Version="8.0.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Features" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.11.0" />
    <!-- RoslynPad Removed -->
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2849.39" />
    <PackageReference Include="WPF-UI" Version="3.0.5" />
    <PackageReference Include="Grpc.Tools" Version="2.67.0" PrivateAssets="All" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Monaco\editor.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CopyProtoc" AfterTargets="Build;Publish">
    <ItemGroup>
      <ProtocTools Include="$(PkgGrpc_Tools)\tools\windows_x64\protoc.exe" />
      <ProtocIncludes Include="$(PkgGrpc_Tools)\tools\google\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(ProtocTools)" DestinationFolder="$(OutDir)\Tools" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(ProtocIncludes)" DestinationFolder="$(OutDir)\Tools\google\%(RecursiveDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(ProtocTools)" DestinationFolder="$(PublishDir)\Tools" SkipUnchangedFiles="true" Condition="'$(PublishDir)' != ''" />
    <Copy SourceFiles="@(ProtocIncludes)" DestinationFolder="$(PublishDir)\Tools\google\%(RecursiveDir)" SkipUnchangedFiles="true" Condition="'$(PublishDir)' != ''" />
  </Target>
</Project>